### ISSUE TITLE
http2: panic serving - runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by man4567890** [nanoscopic/controlfloor#30]
Hi @nanoscopic 
I need some help please..
When I run the ./main run on the remote control floor host, I get the login screen, but when I login with ok and ok, I get this below, my control floor is on a Centos8 machine and the ios_remote_provider is running on a MiniMac
![image](https://user-images.githubusercontent.com/53390181/122340356-77d26380-cf42-11eb-9c6b-3bf5deaabd6e.png)

```
[root@cerc111 controlfloor]# ./main conf
Listen: :8080
HTTPS: true

[root@cerc111 controlfloor]# ./main run
Loading template from devInfo.tmpl
Loading template from devVideo.tmpl
Loading template from error.tmpl
Loading template from providerLogin.tmpl
Loading template from providerRoot.tmpl
Loading template from sidebar.tmpl
Loading template from userLogin.tmpl
Loading template from userRoot.tmpl
Registering user routes
Registering provider routes
Registering device routes
user fail
login ok
2021/06/17 07:56:28 http2: panic serving 192.168.1.159:58732: runtime error: slice bounds out of range [:-1]
goroutine 75 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010358, 0xc000187f8e, 0xc0004c2180)
	/usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
panic(0xb72360, 0xc0004aa0c0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.(*UserHandler).showUserRoot(0xc00034eea0, 0xc000484000)
	/opt/temp/controlfloor/user.go:106 +0x6ca
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.(*UserHandler).NeedUserAuth.func1(0xc000484000)
	/opt/temp/controlfloor/user.go:68 +0xfe
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.(*cfSessionManager).Sessions.func1(0xc000484000)
	/opt/temp/controlfloor/session.go:52 +0xfb
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000312280, 0xc000484000)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x2d0
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000312280, 0xc99d58, 0xc000010358, 0xc000340700)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0003360e0, 0xc99d58, 0xc000010358, 0xc000340700)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.initALPNRequest.ServeHTTP(0xc9b2c0, 0xc000489020, 0xc0002de380, 0xc0003360e0, 0xc99d58, 0xc000010358, 0xc000340700)
	/usr/local/go/src/net/http/server.go:3459 +0x8d
net/http.(*http2serverConn).runHandler(0xc0004c2180, 0xc000010358, 0xc000340700, 0xc00000e840)
	/usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
2021/06/17 07:56:29 http2: panic serving 192.168.1.159:58732: runtime error: slice bounds out of range [:-1]
goroutine 61 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0004a6390, 0xc000187f8e, 0xc0004c2180)
	/usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
panic(0xb72360, 0xc0004aa108)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.(*UserHandler).showUserRoot(0xc00034eea0, 0xc0004843c0)
	/opt/temp/controlfloor/user.go:106 +0x6ca
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.(*UserHandler).NeedUserAuth.func1(0xc0004843c0)
	/opt/temp/controlfloor/user.go:68 +0xfe
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.(*cfSessionManager).Sessions.func1(0xc0004843c0)
	/opt/temp/controlfloor/session.go:52 +0xfb
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000312280, 0xc0004843c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x2d0
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000312280, 0xc99d58, 0xc0004a6390, 0xc0004ca600)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0003360e0, 0xc99d58, 0xc0004a6390, 0xc0004ca600)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.initALPNRequest.ServeHTTP(0xc9b2c0, 0xc000489020, 0xc0002de380, 0xc0003360e0, 0xc99d58, 0xc0004a6390, 0xc0004ca600)
	/usr/local/go/src/net/http/server.go:3459 +0x8d
net/http.(*http2serverConn).runHandler(0xc0004c2180, 0xc0004a6390, 0xc0004ca600, 0xc00048e7f8)
	/usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
2021/06/17 07:56:34 http2: panic serving 192.168.1.159:58732: runtime error: slice bounds out of range [:-1]
goroutine 45 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000286058, 0xc0003adf8e, 0xc0004c2180)
	/usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
panic(0xb72360, 0xc000024780)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.(*UserHandler).showUserRoot(0xc00034eea0, 0xc00039c000)
	/opt/temp/controlfloor/user.go:106 +0x6ca
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.(*UserHandler).NeedUserAuth.func1(0xc00039c000)
	/opt/temp/controlfloor/user.go:68 +0xfe
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
main.(*cfSessionManager).Sessions.func1(0xc00039c000)
	/opt/temp/controlfloor/session.go:52 +0xfb
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000312280, 0xc00039c000)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x2d0
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000312280, 0xc99d58, 0xc000286058, 0xc000294600)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0003360e0, 0xc99d58, 0xc000286058, 0xc000294600)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.initALPNRequest.ServeHTTP(0xc9b2c0, 0xc000489020, 0xc0002de380, 0xc0003360e0, 0xc99d58, 0xc000286058, 0xc000294600)
	/usr/local/go/src/net/http/server.go:3459 +0x8d
net/http.(*http2serverConn).runHandler(0xc0004c2180, 0xc000286058, 0xc000294600, 0xc000296180)
	/usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
```
On the iso_remote_provider (MiniMac), the registration is successful

```
Mac-mini:ios_remote_provider diginetiot$ ./main register
WARN[0000] Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
Enter registration password:
Using default registration password of doreg
{"Success":true,"Password":"b7814af37ee51d1ad4e59ad066b36c76","Existed":false}
Registered and got password b7814af37ee51d1ad4e59ad066b36c76
Mac-mini:ios_remote_provider diginetiot$ 

```

**Comment by man4567890** [comment]
Looking at this again, it seems the code tries to get to a server 192.168.1.159, where my server is on 192.168.1.111
```
Registering device routes
user fail
login ok
2021/06/17 12:26:32 http2: panic serving 192.168.1.159:57837: runtime error: slice bounds out of range [:-1]
goroutine 32 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000090428, 0xc0001d9f8e, 0xc0001acc00)
	/usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
panic(0xb72360, 0xc000468018)

```

**Comment by nanoscopic** [comment]
The crash shown above occurred when there are no devices yet and you visit the device list page. It has been fixed in the latest update.

After registration, and after running provider with `./main run` to provide a device to ControlFloor, the error should also not have occurred previously.

Closing as I believe this described issue is now fixed; feel free to reopen if you still have an issue.
